Feature/nuc 2325 create vuexp cli plugin
vuexp/vue-cli-plugin-vuexp pull request #11
Opened 2019-07-25 15:00 UTC by osmanertem

2019-07-25 16:10 UTC, brendtumi requested changes

2019-07-25 16:10 UTC, brendtumi commented on generator/index.js
> +      'nativescript-imagepicker': 'git://github.com/mylmz10/nativescript-mediapicker.git',
@mylmz10 you need to publish this library. Using git path is not secure.

2019-07-25 16:10 UTC, brendtumi commented on generator/index.js
> +      'vuexp-router': 'git://github.com/vuexp/vuexp-router.git#development',
Using git path is not secure. Please give a compatible version number

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/components/HelloWorld.android.vue
> +  margin-top: 80px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/components/HelloWorld.ios.vue
> +  margin-top: 80px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/components/HelloWorld.native.vue
> +  margin-top: 80px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/components/HelloWorld.vue
> +  margin-top: 40px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/main.js
> +  - !!js/regexp /import App from './App.vue'/
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/main.js
> +import VxpPlugin from "vuexp/src/core/plugins/index.js";
Remove .js extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/main.js
> +import App from '~/App.vue';
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/main.native.js
> +import App from './App.vue';
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/router.js
> +  - !!js/regexp /import Home from '\./views/Home.vue'/
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/styles/style-one.scss
> +  padding: 0 10px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/styles/style-one.less
> +  padding: 0 10px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/advanced/src/views/Home.vue
> +import HelloWorld from 'components/HelloWorld.vue';
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/components/HelloWorld.android.vue
> +  margin-top: 20px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/components/HelloWorld.ios.vue
> +  margin-top: 20px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/components/HelloWorld.native.vue
> +  margin-top: 20px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/main.js
> +  - !!js/regexp /import App from './App.vue'/
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/main.js
> +import App from '~/App.vue';
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/main.native.js
> +import App from './App.vue';
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/router.js
> +  - !!js/regexp /import Home from '\./views/Home.vue'/
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/router.js
> +import Home from '~/views/Home.vue';
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/styles/style-one.less
> +  padding: 0 10px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/styles/style-one.scss
> +  padding: 0 10px;
use unit() function, apply to all page.

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/simple/src/views/Home.vue
> +import HelloWorld from 'components/HelloWorld.vue';
Remove .vue extension by default

2019-07-25 16:10 UTC, brendtumi commented on generator/templates/vue-sfc-template.vue
> +<template native>
We don't have this support?

2019-07-25 16:10 UTC, brendtumi commented on ui.js
> +    id: 'org.nativescript-vue.plugin.cli',
This is need to be updated.

2019-08-21 13:36 UTC, mylmz10 commented on generator/index.js
> +      'nativescript-imagepicker': 'git://github.com/mylmz10/nativescript-mediapicker.git',
Removed unnecessary packages

2019-08-21 13:37 UTC, mylmz10 commented on generator/index.js
> +      'vuexp-router': 'git://github.com/vuexp/vuexp-router.git#development',
It will be changed on release

2019-08-21 13:37 UTC, mylmz10 commented on generator/templates/advanced/src/main.js
> +import VxpPlugin from "vuexp/src/core/plugins/index.js";
Removed

2019-08-21 13:37 UTC, mylmz10 commented on generator/templates/advanced/src/main.js
> +  - !!js/regexp /import App from './App.vue'/
Removed

2019-08-21 13:38 UTC, mylmz10 commented on generator/templates/advanced/src/main.js
> +import App from '~/App.vue';
Removed

2019-08-21 13:38 UTC, mylmz10 commented on generator/templates/advanced/src/main.native.js
> +import App from './App.vue';
Removed

2019-08-21 13:39 UTC, mylmz10 commented on generator/templates/advanced/src/router.js
> +  - !!js/regexp /import Home from '\./views/Home.vue'/
It is the rule of replacing.

2019-08-21 13:49 UTC, mylmz10 commented on generator/templates/advanced/src/views/Home.vue
> +import HelloWorld from 'components/HelloWorld.vue';
Removed

2019-08-21 13:50 UTC, mylmz10 commented on generator/templates/simple/src/main.js
> +  - !!js/regexp /import App from './App.vue'/
It is the rule of replacing

2019-08-21 13:50 UTC, mylmz10 commented on generator/templates/simple/src/main.js
> +import App from '~/App.vue';
Removed

2019-08-21 13:50 UTC, mylmz10 commented on generator/templates/simple/src/main.native.js
> +import App from './App.vue';
Removed

2019-08-21 13:50 UTC, mylmz10 commented on generator/templates/simple/src/router.js
> +  - !!js/regexp /import Home from '\./views/Home.vue'/
It is the rule of replacing

2019-08-21 13:51 UTC, mylmz10 commented on generator/templates/simple/src/router.js
> +import Home from '~/views/Home.vue';
Removed

2019-08-21 13:51 UTC, mylmz10 commented on generator/templates/simple/src/views/Home.vue
> +import HelloWorld from 'components/HelloWorld.vue';
Removed

2019-08-22 07:23 UTC, osmanertem commented on generator/templates/vue-sfc-template.vue
> +<template native>
done

2019-08-22 07:23 UTC, osmanertem commented on ui.js
> +    id: 'org.nativescript-vue.plugin.cli',
done

2019-08-23 08:10 UTC, osmanertem commented on generator/templates/advanced/src/components/HelloWorld.android.vue
> +  margin-top: 80px;
done

2019-08-23 08:10 UTC, osmanertem commented on generator/templates/advanced/src/components/HelloWorld.ios.vue
> +  margin-top: 80px;
done

2019-08-23 08:10 UTC, osmanertem commented on generator/templates/advanced/src/components/HelloWorld.native.vue
> +  margin-top: 80px;
done

2019-08-23 08:10 UTC, osmanertem commented on generator/templates/advanced/src/components/HelloWorld.vue
> +  margin-top: 40px;
done

2019-08-23 08:10 UTC, osmanertem commented on generator/templates/advanced/src/styles/style-one.scss
> +  padding: 0 10px;
done

2019-08-23 08:10 UTC, osmanertem commented on generator/templates/advanced/src/styles/style-one.less
> +  padding: 0 10px;
done

2019-08-23 08:10 UTC, osmanertem commented on generator/templates/simple/src/components/HelloWorld.android.vue
> +  margin-top: 20px;
done

2019-08-23 08:10 UTC, osmanertem commented on generator/templates/simple/src/components/HelloWorld.ios.vue
> +  margin-top: 20px;
done

2019-08-23 08:11 UTC, osmanertem commented on generator/templates/simple/src/components/HelloWorld.native.vue
> +  margin-top: 20px;
done

2019-08-23 08:11 UTC, osmanertem commented on generator/templates/simple/src/styles/style-one.less
> +  padding: 0 10px;
done

2019-08-23 08:11 UTC, osmanertem commented on generator/templates/simple/src/styles/style-one.scss
> +  padding: 0 10px;
done

2019-08-23 14:22 UTC, merged